### Get all note

GET {{api_url}}/note

###

### Post create not

POST {{api_url}}/note
Content-Type: application/json
Accept: application/json
# Authorization: Bearer {{token}}

{
 "title": "Come home" 
}

###

### Get single note

GET {{api_url}}/note/3
Content-Type: application/json
Accept: application/json
# Authorization: Bearer {{token}}

###

### Post Update

PATCH {{api_url}}/note/2
Content-Type: application/json
Accept: application/json
# Authorization: Bearer {{token}}

{
  "Title": "Come home",
  "Content": "No way"
}

###

### Post Delete note

DELETE {{api_url}}/note/1
Content-Type: application/json
Accept: application/json
# Authorization: Bearer {{token}}

{
  
}

###